### ISSUE TITLE
Update the readme and API ?

### ISSUE THREAD

**Issue by leozdgao** [Rezonans/redux-async-connect#58]
It seems the example in readme.md is not working in `v1.0.0-rc2`, it's very confusing and I don't know how to use this in the right way. :cry: 

> Uncaught TypeError: asyncItems.map is not a function

``` js
function wrapWithDispatch(asyncItems) {  
  return asyncItems.map(function (item) {
  ...
```

It seems it should be an array? But in the example:

``` js
@asyncConnect({
  lunch: (params, helpers) => Promise.resolve({id: 1, name: 'Borsch'})
})
```

I don't know how to do next...

**Comment by jac3km4** [comment]
I've just stumbled upon this as well... It seems that with the new API the example should be rewritten like this:

``` javascript
@asyncConnect([{
  key: 'lunch',
  promise: (params, helpers) => Promise.resolve({id: 1, name: 'Borsch'})
}])
```

In short - instead of an object, you should pass an array of objects, each having 2 fields - 'key' and 'promise'.
