### ISSUE TITLE
Getting error: `TypeError: asyncItems.reduce is not a function` with v1.0.0-rc2

### ISSUE THREAD

**Issue by austinmao** [Rezonans/redux-async-connect#40]
When upgrading to v1.0, I am seeing:

```
[1] TypeError: asyncItems.reduce is not a function
[1]     at /Users/austinmao/Sites/aditive-frontend/node_modules/redux-async-connect/lib/ReduxAsyncConnect.js:117:35
[1]     at Array.map (native)
[1]     at loadAsyncConnect (/Users/austinmao/Sites/aditive-frontend/node_modules/redux-async-connect/lib/ReduxAsyncConnect.js:114:68)
[1]     at Object.loadOnServer (/Users/austinmao/Sites/aditive-frontend/node_modules/redux-async-connect/lib/ReduxAsyncConnect.js:142:10)
[1]     at /Users/austinmao/Sites/aditive-frontend/src/server.js:107:7
[1]     at /Users/austinmao/Sites/aditive-frontend/node_modules/react-router/lib/match.js:65:5
[1]     at /Users/austinmao/Sites/aditive-frontend/node_modules/react-router/lib/createTransitionManager.js:110:13
[1]     at done (/Users/austinmao/Sites/aditive-frontend/node_modules/react-router/lib/AsyncUtils.js:81:19)
[1]     at /Users/austinmao/Sites/aditive-frontend/node_modules/react-router/lib/AsyncUtils.js:87:7
[1]     at getComponentsForRoute (/Users/austinmao/Sites/aditive-frontend/node_modules/react-router/lib/getComponents.js:9:5)
```

My code looks like this: https://gist.github.com/austinmao/2b6835414ba740911a5f

Since [API docs](https://github.com/Rezonans/redux-async-connect/blob/v1/docs/API.MD) have not been updated, I cannot tell what has changed to troubleshoot this.

**Comment by obsoke** [comment]
I'm getting a similar error message when trying to build with webpack 1.12.13, but the error I get is for for `map` instead of `reduce`:

```
TypeError: asyncItems.map is not a function
    at wrapWithDispatch (/Users/dale/dev/builders/node_modules/redux-async-connect/lib/asyncConnect.js:115:21)
    at /Users/dale/dev/builders/node_modules/redux-async-connect/lib/asyncConnect.js:139:35
    at Object.<anonymous> (Home.jsx:11:10)
    at Module._compile (module.js:413:34)
    at loader (/Users/dale/dev/builders/node_modules/babel-register/lib/node.js:134:5)
    at Object.require.extensions.(anonymous function) [as .jsx] (/Users/dale/dev/builders/node_modules/babel-registe
r/lib/node.js:144:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
```

The code in question: 

``` js
import React            from 'react';
import { Link }         from 'react-router';
import { connect }      from 'react-redux';
import { asyncConnect } from 'redux-async-connect';
import * as UserActions from '../actions/UserActions.js';

@asyncConnect({
  promise: ({ store: { dispatch, getState } }) => dispatch(UserActions.getAllUsers())
})
@connect(state => ({ todos: state.users }))
export default class Home extends React.Component {
  render () {
    return (
      <div>
        <ul>
          {this.props.todos.toJS().map(item => <li key={item.email}>{item.email}</li>)}
        </ul>
      </div>
    );
  }
}
```

I'm using 1.0.0-rc2.

**Comment by kjanoudi** [comment]
@austinmao @daleee asyncConnect now requires an array as the argument, not a simple object.

replace with: 

``` javascript
@asyncConnect([{
  promise: ({ store: { dispatch, getState } }) => dispatch(UserActions.getAllUsers())
}])
```

**Comment by obsoke** [comment]
@kjanoudi you're right, that was the issue. thanks a lot!

**Comment by austinmao** [comment]
I am not using the decorator. The only place I'm using redux-async-connect is here https://gist.github.com/austinmao/2b6835414ba740911a5f:

```
      /* set static function to dispatch loading of api endpoint */
      static reduxAsyncConnect(params, store) {
        const {dispatch, getState} = store;

        const {
          data: {isLoading, isLoaded}, // data state
        } = getState(); // current state
        const {entity} = api; // entity to load

        // map the url params to an api request object
        const query = {};
        if (paramsMap) {
          /**
           * @function creates query object to request data from server
           * @param  {string} paramKey - name of param from redux-router. e.g., 'campaignId'
           * @param  {string} apiKey - name of key in server. e.g., 'id'
           */
          _.forEach(paramsMap, (paramKey, apiKey) => {
            query[apiKey] = params[paramKey];
          });
        }

        // load if data is not loaded or shouldReload is passed
        if (!isLoaded[entity] || !isLoading[entity] || shouldReload) {
          return dispatch(load(api, query)); // load from server api with constructed query
        }
      }
```

**Comment by sars** [comment]
thanks, @kjanoudi 
@austinmao , sorry for lack of docs, i'm going to update them shortly
using static method is inconvenient in the 1.x version
use decorator instead

**Comment by austinmao** [comment]
@sars Thanks again!

**Comment by bhoomit** [comment]
@sars please update the docs. Would be happy to update and send PR. Thanks!

**Comment by pie6k** [comment]
Well... wouldnt it be better to detect if it's obj and then convert it to 1 element Array? Or to throw some exception explaining that change? I've just lost 1 hour
